### ISSUE TITLE
Include the next lines as part of the __init__ function in the entity

### ISSUE THREAD

**Issue by everner-ds** [MRN-Code/Coinstac_VBM_computation#16]
Your entities are pretty thin wrappers around objects from other libraries. I think it would be nice to handle these lines within the constructor for the entity. You can pass in the parameters when you instantiate the object.

https://github.com/MRN-Code/Coinstac_VBM_computation/blob/0f1b9db6567d583d9c4b67ab4664a14c1fbe87ca/vbm_use_cases_layer.py#L92

**Comment by spanta28** [comment]
In this case, would it not conflict with the idea of entities layer isolation from use cases layer or interface layer?
